# Generated by Django 4.2.7 on 2025-12-08 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('teams', '0001_initial'),
        ('referees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='assistant_referee_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_referee_1_matches', to='referees.referee'),
        ),
        migrations.AddField(
            model_name='match',
            name='assistant_referee_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_referee_2_matches', to='referees.referee'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='teams.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referees.referee'),
        ),
        migrations.AddField(
            model_name='match',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.zone'),
        ),
        migrations.AddField(
            model_name='leaguetable',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_table', to='teams.team'),
        ),
        migrations.AddField(
            model_name='leaguetable',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.zone'),
        ),
        migrations.AddField(
            model_name='goal',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='matches.match'),
        ),
        migrations.AddField(
            model_name='goal',
            name='scorer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='teams.player'),
        ),
        migrations.AddField(
            model_name='goal',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AddField(
            model_name='card',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='matches.match'),
        ),
        migrations.AddField(
            model_name='card',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='teams.player'),
        ),
        migrations.AddField(
            model_name='card',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
        migrations.AlterUniqueTogether(
            name='leaguetable',
            unique_together={('team', 'zone')},
        ),
    ]
