# Generated by Django 4.2.7 on 2025-12-09 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('matches', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('red_card', 'Direct Red Card'), ('double_yellow', 'Two Yellow Cards in One Match'), ('accumulated_yellow', '6 Accumulated Yellow Cards'), ('violent_conduct', 'Violent Conduct'), ('other', 'Other')], max_length=50)),
                ('details', models.TextField(blank=True)),
                ('matches_missed', models.PositiveIntegerField(default=0)),
                ('matches_served', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspensions', to='teams.player')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
