# Generated by Django 4.2.7 on 2025-12-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_suspension'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='round_number',
            field=models.IntegerField(default=1),
        ),
    ]
