# Generated by Django 4.2.7 on 2025-12-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_match_round_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='kickoff_time',
            field=models.CharField(blank=True, help_text='Format: HH:MM (e.g., 15:00 for 3 PM)', max_length=5, null=True),
        ),
    ]
