# Generated by Django 4.2.7 on 2026-01-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_match_kickoff_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguetable',
            name='form',
            field=models.CharField(blank=True, default='', help_text='Last 5 matches form (W/D/L)', max_length=5),
        ),
    ]
