# Generated by Django 6.0.1 on 2026-01-20 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_leaguetable_form'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={},
        ),
    ]
