# Generated by Django 6.0.1 on 2026-02-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_alter_match_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Time when match went live.', null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
