# Generated by Django 4.2.7 on 2025-12-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_player_jersey_number_alter_team_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
