# Generated by Django 4.2.7 on 2025-12-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_add_fkf_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='zone',
            name='fixture_generation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='fixtures_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zone',
            name='match_day_of_week',
            field=models.IntegerField(choices=[(6, 'Saturday'), (0, 'Sunday')], default=6),
        ),
        migrations.AddField(
            model_name='zone',
            name='season_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
