# Generated by Django 4.2.7 on 2025-12-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_team_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='away_jersey_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='away_shorts_color',
            field=models.CharField(blank=True, default='#dc3545', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='away_socks_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='gk_away_jersey_color',
            field=models.CharField(blank=True, default='#ffc107', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='gk_away_shorts_color',
            field=models.CharField(blank=True, default='#ffc107', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='gk_away_socks_color',
            field=models.CharField(blank=True, default='#ffc107', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='gk_home_jersey_color',
            field=models.CharField(blank=True, default='#28a745', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='gk_home_shorts_color',
            field=models.CharField(blank=True, default='#28a745', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='gk_home_socks_color',
            field=models.CharField(blank=True, default='#28a745', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='gk_third_jersey_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='gk_third_shorts_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='gk_third_socks_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='home_jersey_color',
            field=models.CharField(blank=True, default='#dc3545', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='home_shorts_color',
            field=models.CharField(blank=True, default='#ffffff', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='home_socks_color',
            field=models.CharField(blank=True, default='#dc3545', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='third_jersey_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='third_shorts_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='third_socks_color',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
