# Generated by Django 4.2.7 on 2026-01-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_team_away_jersey_color_team_away_shorts_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='away_kit_image',
            field=models.ImageField(blank=True, help_text='Upload away kit design/image', null=True, upload_to='kit_images/'),
        ),
        migrations.AddField(
            model_name='team',
            name='gk_away_kit_image',
            field=models.ImageField(blank=True, help_text='Upload GK away kit design/image', null=True, upload_to='kit_images/'),
        ),
        migrations.AddField(
            model_name='team',
            name='gk_home_kit_image',
            field=models.ImageField(blank=True, help_text='Upload GK home kit design/image', null=True, upload_to='kit_images/'),
        ),
        migrations.AddField(
            model_name='team',
            name='gk_third_kit_image',
            field=models.ImageField(blank=True, help_text='Upload GK third kit design/image', null=True, upload_to='kit_images/'),
        ),
        migrations.AddField(
            model_name='team',
            name='home_kit_image',
            field=models.ImageField(blank=True, help_text='Upload home kit design/image', null=True, upload_to='kit_images/'),
        ),
        migrations.AddField(
            model_name='team',
            name='kit_colors_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='third_kit_image',
            field=models.ImageField(blank=True, help_text='Upload third kit design/image', null=True, upload_to='kit_images/'),
        ),
    ]
