# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_team_away_kit_image_team_gk_away_kit_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='kit_setup_prompt_shown',
            field=models.BooleanField(default=False),
        ),
    ]
