# Generated by Django 4.2.7 on 2026-01-07 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_leaguesettings_transferhistory_transferrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transferrequest',
            new_name='teams_trans_status_541356_idx',
            old_name='teams_trans_status_d8e7b4_idx',
        ),
        migrations.RenameIndex(
            model_name='transferrequest',
            new_name='teams_trans_status_20f570_idx',
            old_name='teams_trans_status_c3a3e5_idx',
        ),
        migrations.RenameIndex(
            model_name='transferrequest',
            new_name='teams_trans_player__e833b6_idx',
            old_name='teams_trans_player__5d5b3e_idx',
        ),
    ]
