# Generated by Django 4.2.7 on 2026-01-07 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_leaguesettings_deadlines'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamOfficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('head_coach', 'Head Coach'), ('assistant_coach', 'Assistant Coach'), ('goalkeeper_coach', 'Goalkeeper Coach'), ('team_doctor', 'Team Doctor'), ('team_patron', 'Team Patron')], max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('caf_license_number', models.CharField(blank=True, help_text='Required for coaches', max_length=50, verbose_name='CAF License Number')),
                ('license_expiry_date', models.DateField(blank=True, null=True, verbose_name='License Expiry Date')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='official_photos/')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officials', to='teams.team')),
            ],
            options={
                'ordering': ['team', 'position'],
                'unique_together': {('team', 'position')},
            },
        ),
    ]
