# Generated by Django 4.2.7 on 2026-01-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_teamofficial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguesettings',
            name='player_registration_closed_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when player registration was closed', null=True),
        ),
        migrations.AddField(
            model_name='leaguesettings',
            name='team_registration_closed_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when team registration was closed', null=True),
        ),
        migrations.AddField(
            model_name='leaguesettings',
            name='transfer_window_closed_date',
            field=models.DateTimeField(blank=True, help_text='Date/time when transfer window was closed', null=True),
        ),
    ]
