# Generated by Django 4.2.7 on 2026-01-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_leaguesettings_player_registration_closed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='clean_sheets',
            field=models.IntegerField(default=0, help_text='Number of clean sheets (for goalkeepers)'),
        ),
    ]
