# Generated by Django 4.2.7 on 2026-01-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_player_clean_sheets'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='suspension_matches',
            field=models.IntegerField(default=0, help_text='Number of matches suspended'),
        ),
    ]
