# Generated by Django 4.2.7 on 2026-01-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0016_player_suspension_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamofficial',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamofficial',
            name='suspension_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamofficial',
            name='suspension_matches',
            field=models.IntegerField(default=0, help_text='Number of matches suspended'),
        ),
        migrations.AddField(
            model_name='teamofficial',
            name='suspension_reason',
            field=models.TextField(blank=True, help_text='Reason for suspension'),
        ),
    ]
