# Generated by Django 4.2.7 on 2026-01-12 15:36

from django.db import migrations, models
import fkf_league.validators


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0017_teamofficial_is_suspended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='phone_number',
            field=models.CharField(help_text='Must be +254 followed by 9 digits (e.g., +254712345678)', max_length=13, unique=True, validators=[fkf_league.validators.validate_kenya_phone]),
        ),
    ]
