# Generated by Django 6.0.1 on 2026-01-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0018_update_phone_number_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fifa_id',
            field=models.CharField(blank=True, help_text='FIFA Connect Player ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='fifa_verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='fifa_verified',
            field=models.BooleanField(default=False, help_text='Verified with FIFA Connect'),
        ),
        migrations.AddField(
            model_name='player',
            name='iprs_verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='iprs_verified',
            field=models.BooleanField(default=False, help_text='Verified with Kenya IPRS'),
        ),
        migrations.AddField(
            model_name='player',
            name='verification_results',
            field=models.JSONField(blank=True, help_text='Detailed verification results from IPRS and FIFA', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='verification_warnings',
            field=models.TextField(blank=True, help_text='Any warnings from verification'),
        ),
    ]
