# Generated by Django 6.0.1 on 2026-02-24 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referees', '0020_squadeditrequest'),
        ('teams', '0019_player_fifa_id_player_fifa_verification_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='tournament_banners/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tournament_logos/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_deadline', models.DateTimeField(help_text='Teams can register until this date/time.')),
                ('format', models.CharField(choices=[('knockout', 'Knockout'), ('group_knockout', 'Group Stage + Knockout'), ('round_robin', 'Round Robin'), ('swiss', 'Swiss System')], default='knockout', max_length=20)),
                ('max_teams', models.PositiveIntegerField(default=16)),
                ('min_squad_size', models.PositiveIntegerField(default=15)),
                ('max_squad_size', models.PositiveIntegerField(default=25)),
                ('group_count', models.PositiveIntegerField(default=4, help_text='Number of groups (only for Group Stage + Knockout format).')),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('registration', 'Registration Open'), ('registration_closed', 'Registration Closed'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=25)),
                ('rules', models.TextField(blank=True, help_text='Tournament rules & regulations.')),
                ('prize_info', models.TextField(blank=True, help_text='Prize breakdown.')),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tournaments', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, help_text='Leave blank for county-wide tournaments.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.zone')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TournamentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Group A', max_length=50)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TournamentTeamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=15)),
                ('rejection_reason', models.TextField(blank=True)),
                ('payment_confirmed', models.BooleanField(default=False)),
                ('seed', models.PositiveIntegerField(blank=True, help_text='Seeding number.', null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_registrations', to='teams.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['seed', 'registered_at'],
                'unique_together': {('tournament', 'team')},
            },
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('group', 'Group Stage'), ('round_of_32', 'Round of 32'), ('round_of_16', 'Round of 16'), ('quarter_final', 'Quarter Final'), ('semi_final', 'Semi Final'), ('third_place', 'Third Place Playoff'), ('final', 'Final')], default='group', max_length=20)),
                ('match_number', models.PositiveIntegerField(help_text='Sequence number within the stage.')),
                ('match_date', models.DateTimeField()),
                ('kickoff_time', models.CharField(blank=True, max_length=5, null=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('home_score', models.PositiveIntegerField(default=0)),
                ('away_score', models.PositiveIntegerField(default=0)),
                ('home_penalties', models.PositiveIntegerField(blank=True, null=True)),
                ('away_penalties', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tournaments.tournamentgroup')),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_matches', to='referees.referee')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_tournament_matches', to='tournaments.tournamentteamregistration')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_tournament_matches', to='tournaments.tournamentteamregistration')),
            ],
            options={
                'ordering': ['match_date', 'match_number'],
                'unique_together': {('tournament', 'stage', 'match_number')},
            },
        ),
        migrations.AddField(
            model_name='tournamentgroup',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='groups', to='tournaments.tournamentteamregistration'),
        ),
        migrations.CreateModel(
            name='TournamentGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField()),
                ('is_penalty', models.BooleanField(default=False)),
                ('is_own_goal', models.BooleanField(default=False)),
                ('scorer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_goals', to='teams.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='tournaments.tournamentmatch')),
                ('team_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournamentteamregistration')),
            ],
            options={
                'ordering': ['minute'],
            },
        ),
        migrations.CreateModel(
            name='TournamentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('yellow', 'Yellow Card'), ('red', 'Red Card')], max_length=10)),
                ('minute', models.PositiveIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_cards', to='teams.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='tournaments.tournamentmatch')),
                ('team_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournamentteamregistration')),
            ],
            options={
                'ordering': ['minute'],
            },
        ),
        migrations.CreateModel(
            name='TournamentPlayerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_number', models.PositiveIntegerField(help_text='Jersey number for this tournament.')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='registered', max_length=15)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_registrations', to='teams.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_registrations', to='tournaments.tournament')),
                ('team_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_registrations', to='tournaments.tournamentteamregistration')),
            ],
            options={
                'ordering': ['jersey_number'],
                'unique_together': {('team_registration', 'jersey_number'), ('tournament', 'player')},
            },
        ),
        migrations.CreateModel(
            name='TournamentGroupStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.PositiveIntegerField(default=0)),
                ('won', models.PositiveIntegerField(default=0)),
                ('drawn', models.PositiveIntegerField(default=0)),
                ('lost', models.PositiveIntegerField(default=0)),
                ('goals_for', models.PositiveIntegerField(default=0)),
                ('goals_against', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tournaments.tournamentgroup')),
                ('team_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournamentteamregistration')),
            ],
            options={
                'ordering': ['-won', '-goals_for', 'goals_against'],
                'unique_together': {('group', 'team_registration')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='tournamentgroup',
            unique_together={('tournament', 'name')},
        ),
    ]
