# Generated by Django 6.0.1 on 2026-02-24 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0020_squadeditrequest'),
        ('teams', '0019_player_fifa_id_player_fifa_verification_date_and_more'),
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('id_number', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tournament_external_players/')),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('FW', 'Forward')], max_length=2)),
                ('jersey_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['jersey_number'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='tournamentplayerregistration',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentteamregistration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tournament',
            name='allow_external_teams',
            field=models.BooleanField(default=True, help_text='Allow teams not in the FKF County League to register.'),
        ),
        migrations.AddField(
            model_name='tournamentteamregistration',
            name='team_type',
            field=models.CharField(choices=[('league', 'FKF League Team'), ('external', 'External Team')], default='league', max_length=10),
        ),
        migrations.AlterField(
            model_name='tournamentcard',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_cards', to='teams.player'),
        ),
        migrations.AlterField(
            model_name='tournamentgoal',
            name='scorer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_goals', to='teams.player'),
        ),
        migrations.AlterField(
            model_name='tournamentplayerregistration',
            name='player',
            field=models.ForeignKey(blank=True, help_text='League player (if team is from the league).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_registrations', to='teams.player'),
        ),
        migrations.AlterField(
            model_name='tournamentteamregistration',
            name='team',
            field=models.ForeignKey(blank=True, help_text='For teams already in the FKF County League.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_registrations', to='teams.team'),
        ),
        migrations.AddField(
            model_name='tournamentcard',
            name='external_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_cards', to='tournaments.externalplayer'),
        ),
        migrations.AddField(
            model_name='tournamentgoal',
            name='external_scorer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_goals', to='tournaments.externalplayer'),
        ),
        migrations.AddField(
            model_name='tournamentplayerregistration',
            name='external_player',
            field=models.ForeignKey(blank=True, help_text='External player (if team is external).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_registrations', to='tournaments.externalplayer'),
        ),
        migrations.CreateModel(
            name='ExternalTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tournament_external_logos/')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('home_ground', models.CharField(blank=True, max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('home_jersey_color', models.CharField(blank=True, default='#dc3545', max_length=50)),
                ('away_jersey_color', models.CharField(blank=True, default='#ffffff', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_teams_managed', to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_teams', to='tournaments.tournament')),
            ],
            options={
                'ordering': ['team_name'],
                'unique_together': {('tournament', 'team_name')},
            },
        ),
        migrations.AddField(
            model_name='externalplayer',
            name='external_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournaments.externalteam'),
        ),
        migrations.AddField(
            model_name='tournamentteamregistration',
            name='external_team',
            field=models.ForeignKey(blank=True, help_text='For teams NOT in the FKF County League.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_registrations', to='tournaments.externalteam'),
        ),
        migrations.CreateModel(
            name='TournamentMatchOfficials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Appointment'), ('APPOINTED', 'Appointed'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Match Completed')], default='PENDING', max_length=20)),
                ('appointed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('appointed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('assistant_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_appointed_ar1', to='referees.referee')),
                ('assistant_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_appointed_ar2', to='referees.referee')),
                ('fourth_official', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_appointed_fourth', to='referees.referee')),
                ('main_referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_appointed_main', to='referees.referee')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officials', to='tournaments.tournamentmatch')),
                ('match_commissioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_appointed_commissioner', to='referees.referee')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='externalplayer',
            unique_together={('external_team', 'jersey_number')},
        ),
    ]
