# Generated by Django 6.0.1 on 2026-02-25 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0020_squadeditrequest'),
        ('teams', '0019_player_fifa_id_player_fifa_verification_date_and_more'),
        ('tournaments', '0002_externalplayer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='extra_time_duration',
            field=models.PositiveIntegerField(default=30, help_text='Extra time duration (if applicable) in minutes.'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='half_duration',
            field=models.PositiveIntegerField(default=45, help_text='Duration of each half in minutes.'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='match_duration',
            field=models.PositiveIntegerField(default=90, help_text='Total match duration in minutes (e.g. 60, 70, 80, 90).'),
        ),
        migrations.CreateModel(
            name='TournamentMatchdaySquad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Submission'), ('submitted', 'Submitted – Awaiting Referee Approval'), ('approved', 'Approved by Referee'), ('locked', 'Locked (Match Started)')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_approved_squads', to='referees.referee')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchday_squads', to='tournaments.tournamentmatch')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_submitted_squads', to=settings.AUTH_USER_MODEL)),
                ('team_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchday_squads', to='tournaments.tournamentteamregistration')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('match', 'team_registration')},
            },
        ),
        migrations.CreateModel(
            name='TournamentSquadPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starting', models.BooleanField(default=False)),
                ('position_order', models.IntegerField(default=0)),
                ('jersey_number', models.PositiveIntegerField()),
                ('external_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_squad_entries', to='tournaments.externalplayer')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_squad_entries', to='teams.player')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_players', to='tournaments.tournamentmatchdaysquad')),
            ],
            options={
                'ordering': ['-is_starting', 'position_order', 'jersey_number'],
            },
        ),
    ]
