# Generated by Django 4.2.7 on 2025-12-10 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referee',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referee',
            name='fkf_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='FKF License Number'),
        ),
        migrations.AlterField(
            model_name='matchreport',
            name='pitch_conditions',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('very_poor', 'Very Poor')], default='good', max_length=20),
        ),
        migrations.AlterField(
            model_name='referee',
            name='license_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Referee License Number'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referee', to=settings.AUTH_USER_MODEL),
        ),
    ]
