# Generated by Django 4.2.7 on 2025-12-10 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_suspension'),
        ('teams', '0002_alter_player_jersey_number_alter_team_email_and_more'),
        ('referees', '0002_referee_county_referee_fkf_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchreport',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='matchreport',
            name='major_incidents',
        ),
        migrations.RemoveField(
            model_name='matchreport',
            name='pitch_conditions',
        ),
        migrations.RemoveField(
            model_name='matchreport',
            name='weather_conditions',
        ),
        migrations.AddField(
            model_name='matchreport',
            name='entered_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='entered_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='entered_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='league_level',
            field=models.CharField(default='FKF County League', max_length=50),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='match_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Match Number'),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='penalties_not_converted',
            field=models.TextField(blank=True, verbose_name='Penalties Awarded but Not Converted'),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='received_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='received_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='round_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Round'),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='serious_incidents',
            field=models.TextField(blank=True, verbose_name='Serious Incidents'),
        ),
        migrations.AlterField(
            model_name='matchreport',
            name='referee_comments',
            field=models.TextField(blank=True, verbose_name='Referee Comments'),
        ),
        migrations.CreateModel(
            name='TeamOfficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('coach', 'Coach'), ('team_manager', 'Team Manager'), ('assistant_coach', 'Assistant Coach'), ('doctor', 'Team Doctor'), ('physio', 'Physiotherapist'), ('kit_manager', 'Kit Manager'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_officials', to='matches.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'ordering': ['team', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField()),
                ('jersey_out', models.IntegerField()),
                ('jersey_in', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='matches.match')),
                ('player_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituted_in', to='teams.player')),
                ('player_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituted_out', to='teams.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'ordering': ['minute'],
            },
        ),
        migrations.CreateModel(
            name='MatchVenueDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_changing_room', models.BooleanField(default=True, verbose_name='Home Changing Room')),
                ('away_changing_room', models.BooleanField(default=True, verbose_name='Away Changing Room')),
                ('seating_arrangement', models.BooleanField(default=True, verbose_name='Seating Arrangement')),
                ('ball_boys', models.BooleanField(default=True, verbose_name='Ball Boys Available')),
                ('security_personnel', models.BooleanField(default=True, verbose_name='Security Personnel')),
                ('field_markings', models.BooleanField(default=True, verbose_name='Field Markings')),
                ('ambulance', models.BooleanField(default=True, verbose_name='Ambulance Available')),
                ('stretcher', models.BooleanField(default=True, verbose_name='Stretcher Available')),
                ('pitch_condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('very_poor', 'Very Poor')], default='good', max_length=20)),
                ('weather_before', models.CharField(blank=True, max_length=100, verbose_name='Weather Before Game')),
                ('weather_during', models.CharField(blank=True, max_length=100, verbose_name='Weather During Game')),
                ('first_half_start', models.TimeField(blank=True, null=True)),
                ('first_half_end', models.TimeField(blank=True, null=True)),
                ('first_half_duration', models.IntegerField(blank=True, null=True, verbose_name='First Half Duration (mins)')),
                ('second_half_start', models.TimeField(blank=True, null=True)),
                ('second_half_end', models.TimeField(blank=True, null=True)),
                ('second_half_duration', models.IntegerField(blank=True, null=True, verbose_name='Second Half Duration (mins)')),
                ('attendance', models.IntegerField(blank=True, null=True, verbose_name='Match Attendance')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venue_details', to='matches.match')),
            ],
        ),
        migrations.CreateModel(
            name='MatchGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField()),
                ('goal_type', models.CharField(choices=[('normal', 'Normal Goal'), ('penalty', 'Penalty'), ('own_goal', 'Own Goal'), ('free_kick', 'Free Kick')], default='normal', max_length=20)),
                ('jersey_number', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('assist_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referee_goal_assists', to='teams.player')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_goals', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee_match_goals', to='teams.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'ordering': ['minute'],
            },
        ),
        migrations.CreateModel(
            name='Expulsion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField()),
                ('reason', models.TextField()),
                ('jersey_number', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expulsions', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'ordering': ['minute'],
            },
        ),
        migrations.CreateModel(
            name='Caution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField()),
                ('reason', models.TextField()),
                ('jersey_number', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cautions', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'ordering': ['minute'],
            },
        ),
        migrations.CreateModel(
            name='StartingLineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_number', models.IntegerField()),
                ('position', models.CharField(blank=True, max_length=50)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_lineups', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'ordering': ['jersey_number'],
                'unique_together': {('match', 'team', 'player')},
            },
        ),
        migrations.CreateModel(
            name='ReservePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_number', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_players', to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'ordering': ['jersey_number'],
                'unique_together': {('match', 'team', 'player')},
            },
        ),
        migrations.CreateModel(
            name='PlayingKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('condition', models.BooleanField(default=True, help_text='√ = Good, X = Not Good')),
                ('notes', models.TextField(blank=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playing_kits', to='matches.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'unique_together': {('match', 'team', 'item')},
            },
        ),
        migrations.CreateModel(
            name='MatchOfficials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('centre', 'Centre Referee'), ('assistant_1', 'Assistant Referee 1'), ('assistant_2', 'Assistant Referee 2'), ('reserve', 'Reserve Referee'), ('commissioner', 'Match Commissioner')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officials', to='matches.match')),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referees.referee')),
            ],
            options={
                'unique_together': {('match', 'position')},
            },
        ),
    ]
