# Generated by Django 4.2.7 on 2025-12-11 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referees', '0003_remove_matchreport_attendance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caution',
            options={'ordering': ['minute'], 'verbose_name': 'Caution (Yellow Card)', 'verbose_name_plural': 'Cautions (Yellow Cards)'},
        ),
        migrations.AlterModelOptions(
            name='expulsion',
            options={'ordering': ['minute'], 'verbose_name': 'Expulsion (Red Card)', 'verbose_name_plural': 'Expulsions (Red Cards)'},
        ),
        migrations.AlterModelOptions(
            name='matchgoal',
            options={'ordering': ['minute'], 'verbose_name': 'Match Goal', 'verbose_name_plural': 'Match Goals'},
        ),
        migrations.AlterModelOptions(
            name='matchofficials',
            options={'verbose_name': 'Match Official', 'verbose_name_plural': 'Match Officials'},
        ),
        migrations.AlterModelOptions(
            name='matchreport',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Match Report', 'verbose_name_plural': 'Match Reports'},
        ),
        migrations.AlterModelOptions(
            name='matchvenuedetails',
            options={'verbose_name': 'Match Venue Detail', 'verbose_name_plural': 'Match Venue Details'},
        ),
        migrations.AlterModelOptions(
            name='playingkit',
            options={'verbose_name': 'Playing Kit', 'verbose_name_plural': 'Playing Kits'},
        ),
        migrations.AlterModelOptions(
            name='referee',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Referee', 'verbose_name_plural': 'Referees'},
        ),
        migrations.AlterModelOptions(
            name='reserveplayer',
            options={'ordering': ['jersey_number'], 'verbose_name': 'Reserve Player', 'verbose_name_plural': 'Reserve Players'},
        ),
        migrations.AlterModelOptions(
            name='startinglineup',
            options={'ordering': ['jersey_number'], 'verbose_name': 'Starting Lineup', 'verbose_name_plural': 'Starting Lineups'},
        ),
        migrations.AlterModelOptions(
            name='substitution',
            options={'ordering': ['minute'], 'verbose_name': 'Substitution', 'verbose_name_plural': 'Substitutions'},
        ),
        migrations.AlterModelOptions(
            name='teamofficial',
            options={'ordering': ['team', 'position'], 'verbose_name': 'Team Official', 'verbose_name_plural': 'Team Officials'},
        ),
        migrations.AddField(
            model_name='referee',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referee',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who approved this referee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_referees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referee',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if applicable'),
        ),
        migrations.AddField(
            model_name='referee',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status of the referee', max_length=20),
        ),
        migrations.AddField(
            model_name='referee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='playingkit',
            name='item',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('shorts', 'Shorts'), ('stockings', 'Stockings'), ('goalkeeper_jersey', 'Goalkeeper Jersey'), ('goalkeeper_shorts', 'Goalkeeper Shorts/Trousers'), ('goalkeeper_stockings', 'Goalkeeper Stockings')], max_length=50),
        ),
    ]
