# Generated by Django 4.2.7 on 2025-12-16 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0005_match_kickoff_time'),
        ('referees', '0004_alter_caution_options_alter_expulsion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caution',
            options={'ordering': ['minute']},
        ),
        migrations.AlterModelOptions(
            name='expulsion',
            options={'ordering': ['minute']},
        ),
        migrations.AlterModelOptions(
            name='matchgoal',
            options={'ordering': ['minute']},
        ),
        migrations.AlterModelOptions(
            name='matchofficials',
            options={'ordering': ['match__match_date'], 'verbose_name_plural': 'Match Officials'},
        ),
        migrations.AlterModelOptions(
            name='matchreport',
            options={},
        ),
        migrations.AlterModelOptions(
            name='matchvenuedetails',
            options={},
        ),
        migrations.AlterModelOptions(
            name='playingkit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reserveplayer',
            options={'ordering': ['jersey_number']},
        ),
        migrations.AlterModelOptions(
            name='startinglineup',
            options={'ordering': ['jersey_number']},
        ),
        migrations.AlterModelOptions(
            name='substitution',
            options={'ordering': ['minute']},
        ),
        migrations.AlterModelOptions(
            name='teamofficial',
            options={'ordering': ['team', 'position']},
        ),
        migrations.RenameField(
            model_name='matchofficials',
            old_name='mobile',
            new_name='ar1_mobile',
        ),
        migrations.RenameField(
            model_name='matchofficials',
            old_name='name',
            new_name='ar1_name',
        ),
        migrations.AlterUniqueTogether(
            name='matchofficials',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='matchreport',
            name='entered_by',
        ),
        migrations.RemoveField(
            model_name='matchreport',
            name='entered_date',
        ),
        migrations.RemoveField(
            model_name='matchreport',
            name='entered_time',
        ),
        migrations.RemoveField(
            model_name='matchreport',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='matchreport',
            name='received_date',
        ),
        migrations.RemoveField(
            model_name='matchreport',
            name='received_time',
        ),
        migrations.RemoveField(
            model_name='referee',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='referee',
            name='license_number',
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='appointment_made_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='appointment_made_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referee_appointments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='ar1_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='ar1_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='ar2_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='ar2_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='ar2_mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='ar2_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='assistant_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointed_as_assistant1', to='referees.referee'),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='assistant_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointed_as_assistant2', to='referees.referee'),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='avar1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointed_as_avar1', to='referees.referee'),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='fourth_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='fourth_official',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointed_as_fourth', to='referees.referee'),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='main_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='main_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='main_referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointed_as_main', to='referees.referee'),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='main_referee_mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='main_referee_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='match_commissioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointed_as_commissioner', to='referees.referee'),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='reserve_assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointed_as_reserve_assistant', to='referees.referee'),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='reserve_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='reserve_referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointed_as_reserve', to='referees.referee'),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Appointment'), ('APPOINTED', 'Appointed - Awaiting Confirmation'), ('CONFIRMED', 'Confirmed by All'), ('REJECTED', 'Some Officials Rejected'), ('ALTERNATE', 'Using Alternate Officials'), ('COMPLETED', 'Match Completed'), ('CANCELLED', 'Match Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='var',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointed_as_var', to='referees.referee'),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='var_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referee',
            name='level',
            field=models.CharField(blank=True, choices=[('fifa_elite', 'FIFA Elite'), ('fkf_premier', 'FKF Premier League'), ('fkf_national_super', 'FKF National Super League'), ('fkf_division_1', 'FKF Division 1'), ('fkf_division_2', 'FKF Division 2'), ('fkf_county', 'FKF County League'), ('grassroot', 'Grassroot')], max_length=30, null=True, verbose_name='Referee Level'),
        ),
        migrations.AddField(
            model_name='referee',
            name='suspension_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='referee',
            name='unique_id',
            field=models.CharField(blank=True, help_text='Auto-generated login ID (REF-YYYY-XXXX)', max_length=20, unique=True, verbose_name='Unique Referee ID'),
        ),
        migrations.AlterField(
            model_name='matchofficials',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officials', to='matches.match'),
        ),
        migrations.AlterField(
            model_name='matchreport',
            name='match_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='matchreport',
            name='penalties_not_converted',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='matchreport',
            name='referee_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='matchreport',
            name='round_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='matchreport',
            name='serious_incidents',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='matchvenuedetails',
            name='ambulance',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='matchvenuedetails',
            name='attendance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchvenuedetails',
            name='away_changing_room',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='matchvenuedetails',
            name='ball_boys',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='matchvenuedetails',
            name='field_markings',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='matchvenuedetails',
            name='first_half_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchvenuedetails',
            name='home_changing_room',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='matchvenuedetails',
            name='seating_arrangement',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='matchvenuedetails',
            name='second_half_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchvenuedetails',
            name='security_personnel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='matchvenuedetails',
            name='stretcher',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='matchvenuedetails',
            name='weather_before',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='matchvenuedetails',
            name='weather_during',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='playingkit',
            name='condition',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='referee',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_referees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referee',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='referee',
            name='fkf_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True, verbose_name='FKF License Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referee',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='National ID Number'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='referee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='referee',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='referee',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Linked user account (created after approval)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='matchofficials',
            name='position',
        ),
        migrations.RemoveField(
            model_name='matchofficials',
            name='referee',
        ),
        migrations.CreateModel(
            name='RefereeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='referees.referee')),
            ],
            options={
                'verbose_name_plural': 'Referee Availabilities',
                'ordering': ['-date'],
                'unique_together': {('referee', 'date')},
            },
        ),
    ]
