# Generated by Django 4.2.7 on 2025-12-16 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0005_alter_caution_options_alter_expulsion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchreport',
            options={'permissions': [('submit_match_report', 'Can submit match report'), ('approve_match_report', 'Can approve match report'), ('reject_match_report', 'Can reject match report')]},
        ),
    ]
