# Generated by Django 4.2.7 on 2025-12-16 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0006_alter_matchreport_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchofficials',
            options={'ordering': ['match__match_date'], 'permissions': [('appoint_referees', 'Can appoint match officials'), ('replace_referee', 'Can replace appointed referee'), ('confirm_appointment', 'Can confirm referee appointment')], 'verbose_name_plural': 'Match Officials'},
        ),
        migrations.AlterModelOptions(
            name='referee',
            options={'ordering': ['last_name', 'first_name'], 'permissions': [('manage_referees', 'Can manage referees (approve/reject/suspend)')], 'verbose_name': 'Referee', 'verbose_name_plural': 'Referees'},
        ),
    ]
