# Generated by Django 4.2.7 on 2025-12-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0007_alter_matchofficials_options_alter_referee_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referee',
            name='unique_id',
            field=models.CharField(blank=True, help_text='Auto-generated login ID (REF-YYYY-XXXX)', max_length=20, null=True, unique=True, verbose_name='Unique Referee ID'),
        ),
    ]
