# Generated by Django 4.2.7 on 2026-01-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0009_prematchmeetingform'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchofficials',
            name='commissioner_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='commissioner_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
