# Generated by Django 4.2.7 on 2026-01-12 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0006_leaguetable_form'),
        ('teams', '0018_update_phone_number_fields'),
        ('referees', '0012_alter_referee_county'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchdaySquad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Submission'), ('submitted', 'Submitted - Awaiting Referee Approval'), ('approved', 'Approved by Referee'), ('locked', 'Locked (Match Started)')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_squads', to='referees.referee')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchday_squads', to='matches.match')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_squads', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('match', 'team')},
            },
        ),
        migrations.CreateModel(
            name='SubstitutionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField(blank=True, help_text='Match minute when substitution occurs', null=True)),
                ('sub_type', models.CharField(choices=[('normal', 'Normal Substitution'), ('injury', 'Injury Substitution'), ('tactical', 'Tactical Substitution'), ('concussion', 'Concussion Substitution (6th Sub)')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('effected_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('effected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='effected_subs', to='referees.referee')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitution_requests', to='matches.match')),
                ('player_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_requests_in', to='teams.player')),
                ('player_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_requests_out', to='teams.player')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_requests', to=settings.AUTH_USER_MODEL)),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitution_requests', to='referees.matchdaysquad')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'ordering': ['minute', 'requested_at'],
            },
        ),
        migrations.CreateModel(
            name='SubstitutionOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_number', models.IntegerField(help_text='1st, 2nd, or 3rd opportunity')),
                ('minute', models.IntegerField()),
                ('is_halftime', models.BooleanField(default=False, help_text="Halftime subs don't count toward 3 opportunities")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_opportunities', to='matches.match')),
                ('substitutions', models.ManyToManyField(related_name='opportunities', to='referees.substitutionrequest')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'ordering': ['minute'],
                'unique_together': {('match', 'team', 'opportunity_number')},
            },
        ),
        migrations.CreateModel(
            name='SquadPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_starting', models.BooleanField(default=False, help_text='Is this player in the starting 11?')),
                ('position_order', models.IntegerField(default=0, help_text='Display order in starting lineup')),
                ('jersey_number', models.IntegerField()),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.player')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_players', to='referees.matchdaysquad')),
            ],
            options={
                'ordering': ['-is_starting', 'position_order', 'jersey_number'],
                'unique_together': {('squad', 'player')},
            },
        ),
    ]
