# Generated by Django 4.2.7 on 2026-01-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0013_matchdaysquad_substitutionrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchofficials',
            name='ar1_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='ar1_rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='ar1_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='ar2_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='ar2_rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='ar2_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='commissioner_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='commissioner_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='fourth_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='fourth_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='main_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='main_rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='main_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='reserve_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='reserve_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='var_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matchofficials',
            name='var_rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
