# Generated by Django 4.2.7 on 2026-01-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0014_matchofficials_ar1_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referee',
            name='specialization',
            field=models.CharField(blank=True, choices=[('REFEREE', 'Referee'), ('ASSISTANT_REFEREE', 'Assistant Referee'), ('MATCH_COMMISSIONER', 'Match Commissioner')], help_text='Select your primary specialization: Referee, Assistant Referee, or Match Commissioner', max_length=30, null=True, verbose_name='Specialization'),
        ),
    ]
