# Generated by Django 4.2.7 on 2026-01-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0015_referee_specialization'),
    ]

    operations = [
    ]
