# Generated by Django 4.2.7 on 2026-01-14 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0016_auto_20260114_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchofficials',
            name='avar2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointed_as_avar2', to='referees.referee'),
        ),
    ]
