# Generated by Django 4.2.7 on 2026-01-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0017_matchofficials_avar2'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserveplayer',
            name='not_working',
            field=models.BooleanField(default=False, help_text='Tick if this reserve player was not available/working.'),
        ),
    ]
