# Generated by Django 4.2.7 on 2026-01-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0018_reserveplayer_not_working'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prematchmeetingform',
            name='away_gk_stocking',
        ),
        migrations.RemoveField(
            model_name='prematchmeetingform',
            name='home_gk_stocking',
        ),
        migrations.AddField(
            model_name='prematchmeetingform',
            name='away_playing_unit_shirt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='prematchmeetingform',
            name='away_playing_unit_short',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='prematchmeetingform',
            name='away_playing_unit_stocking',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='prematchmeetingform',
            name='home_playing_unit_shirt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='prematchmeetingform',
            name='home_playing_unit_short',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='prematchmeetingform',
            name='home_playing_unit_stocking',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
