# Generated by Django 6.0.1 on 2026-01-20 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0019_remove_prematchmeetingform_away_gk_stocking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SquadEditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for requesting edit')),
                ('status', models.CharField(choices=[('pending', 'Pending Referee Review'), ('approved', 'Approved - Can Edit'), ('declined', 'Declined by Referee')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, help_text="Referee's review notes")),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_edit_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referees.referee')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='referees.matchdaysquad')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
